import { useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Icon } from "../components/Icon";
import { stepDependents, useImpactReports } from "../state/impactReports";
import { askMainAgent } from "../utils/agentAsk";
import { CATEGORY_LABELS, parseReviewGuide, type GuideStep } from "./reviewGuideSteps";

const GUIDE_MODEL = "sonnet";
const GUIDE_EFFORT = "high";

/** Guides + progress survive tab switches and remounts within one app run;
 * regeneration is always one click away, so nothing here needs persisting.
 * `signature` records the diff the guide was built against, so a moved diff
 * shows as stale instead of silently guiding through an outdated roadmap. */
const guideCache = new Map<string, { steps: GuideStep[]; done: Set<number>; signature: string }>();

/** What the guide was generated against: the merge-base plus the file set. */
function diffSignature(mergeBase: string, files: string[]): string {
  return `${mergeBase}:${[...files].sort().join("\n")}`;
}

/**
 * The review roadmap: the branch's main agent reads the whole diff and lays
 * out the order a human should walk it in — core logic first-class, wiring
 * next, boilerplate last — each step clickable to jump the viewer to its
 * files. The agent proposes; checking off steps is the human's own pacing.
 */
export function ReviewGuide({
  branch,
  mergeBase,
  knownFiles,
  onSelect,
  viewed,
  onMarkViewed,
}: {
  branch: string;
  /** The current snapshot's merge-base — part of the staleness signature. */
  mergeBase: string;
  knownFiles: string[];
  onSelect: (path: string) => void;
  /** The diff list's per-file viewed set — the guide shows progress against it. */
  viewed: Set<string>;
  /** Mark/unmark a step's files as viewed alongside the check-off. */
  onMarkViewed: (paths: string[], on: boolean) => void;
}) {
  const cached = guideCache.get(branch);
  const [steps, setSteps] = useState<GuideStep[] | null>(cached?.steps ?? null);
  const [done, setDone] = useState<Set<number>>(cached?.done ?? new Set());
  const [signature, setSignature] = useState<string | null>(cached?.signature ?? null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(true);
  // The branch's blast radius (if the user computed one) — steps whose files
  // have outside dependents get flagged, so the reviewer knows where a change
  // ripples beyond the diff and deserves the slow read.
  const impactReport = useImpactReports((s) => s.byBranch[branch]?.report);

  const currentSignature = useMemo(
    () => diffSignature(mergeBase, knownFiles),
    [mergeBase, knownFiles],
  );
  const stale = steps !== null && signature !== null && signature !== currentSignature;

  const generate = async () => {
    setBusy(true);
    setError(null);
    try {
      const prompt = await invoke<string>("render_review_guide_prompt", { branch }).catch(
        (e: unknown) => {
          setError(String(e));
          return null;
        },
      );
      if (!prompt) return;
      const result = await askMainAgent({
        branch,
        prompt,
        model: GUIDE_MODEL,
        effort: GUIDE_EFFORT,
      });
      if (!result?.ok || !result.text) {
        setError("The agent's turn failed — try again.");
        return;
      }
      const parsed = parseReviewGuide(result.text, knownFiles);
      if (!parsed) {
        setError("Could not parse a roadmap out of the reply — try regenerating.");
        return;
      }
      const fresh = new Set<number>();
      setSteps(parsed);
      setDone(fresh);
      setSignature(currentSignature);
      setOpen(true);
      guideCache.set(branch, { steps: parsed, done: fresh, signature: currentSignature });
    } catch (e) {
      // A thrown step (ensureMain, send) must surface, not die as an
      // unhandled rejection with the panel silently idle.
      setError(String(e));
    } finally {
      setBusy(false);
    }
  };

  const toggleDone = (index: number) => {
    const nowDone = !done.has(index);
    setDone((prev) => {
      const next = new Set(prev);
      if (nowDone) next.add(index);
      else next.delete(index);
      const entry = guideCache.get(branch);
      if (entry) guideCache.set(branch, { ...entry, done: next });
      return next;
    });
    // Checking off a step is reviewing its files — keep the diff list's
    // checkmarks in step so the roadmap doubles as the review checklist.
    const files = steps?.[index]?.files ?? [];
    if (files.length > 0) onMarkViewed(files, nowDone);
  };

  return (
    <div className="review-guide">
      <div className="review-guide-header">
        <button
          className="small ghost review-guide-toggle"
          onClick={() => setOpen((o) => !o)}
          title="A step-by-step reading order for this diff, generated by the main agent"
        >
          <Icon name={open ? "chevron-down" : "chevron-right"} size={12} /> Review guide
          {steps && ` · ${done.size}/${steps.length}`}
        </button>
        {stale && (
          <span
            className="review-guide-stale"
            title="The diff changed since this guide was built — regenerate it"
          >
            stale
          </span>
        )}
        <button
          className="small ghost"
          disabled={busy}
          onClick={() => void generate()}
          title="Ask the main agent to lay out the review order (core logic first, boilerplate last)"
        >
          {busy ? <Icon name="spinner" spin size={12} /> : <Icon name="bot" size={12} />}
          {steps ? "" : " Guide me"}
        </button>
      </div>

      {error && (
        <p className="hint warn" onClick={() => setError(null)} title="Click to dismiss">
          {error}
        </p>
      )}
      {busy && !steps && <p className="review-guide-empty">Reading the diff…</p>}

      {open && steps && (
        <ol className="review-guide-steps">
          {steps.map((step, i) => (
            <li key={i} className={`review-guide-step ${done.has(i) ? "done" : ""}`}>
              <div className="review-guide-step-head">
                <input
                  type="checkbox"
                  checked={done.has(i)}
                  onChange={() => toggleDone(i)}
                  title="Mark this step reviewed"
                />
                <button
                  className="review-guide-step-title"
                  onClick={() => onSelect(step.files[0])}
                  title={step.why || step.title}
                >
                  {step.title}
                </button>
                <span className={`review-guide-cat ${step.category}`}>
                  {CATEGORY_LABELS[step.category]}
                </span>
                {(() => {
                  const dependents = stepDependents(impactReport, step.files);
                  return dependents > 0 ? (
                    <span
                      className="review-guide-impact"
                      title={`${dependents} file${dependents > 1 ? "s" : ""} outside this diff reference what this step changes (blast radius)`}
                    >
                      <Icon name="alert" size={10} /> {dependents}
                    </span>
                  ) : null;
                })()}
              </div>
              {step.why && <p className="review-guide-why">{step.why}</p>}
              <div className="review-guide-files">
                {step.files.map((f) => (
                  <button
                    key={f}
                    className={`review-guide-file${viewed.has(f) ? " viewed" : ""}`}
                    onClick={() => onSelect(f)}
                    title={`${f}${viewed.has(f) ? " — viewed" : ""}`}
                  >
                    {f.split("/").pop()}
                  </button>
                ))}
                {step.files.length > 1 && (
                  <span className="review-guide-progress">
                    {step.files.filter((f) => viewed.has(f)).length}/{step.files.length} viewed
                  </span>
                )}
              </div>
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}
