import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Icon } from "../components/Icon";
import { askMainAgent } from "../utils/agentAsk";
import { CATEGORY_LABELS, parseReviewGuide, type GuideStep } from "./reviewGuideSteps";

const GUIDE_MODEL = "sonnet";
const GUIDE_EFFORT = "high";

/** Guides + progress survive tab switches and remounts within one app run;
 * regeneration is always one click away, so nothing here needs persisting. */
const guideCache = new Map<string, { steps: GuideStep[]; done: Set<number> }>();

/**
 * The review roadmap: the branch's main agent reads the whole diff and lays
 * out the order a human should walk it in — core logic first-class, wiring
 * next, boilerplate last — each step clickable to jump the viewer to its
 * files. The agent proposes; checking off steps is the human's own pacing.
 */
export function ReviewGuide({
  branch,
  knownFiles,
  onSelect,
}: {
  branch: string;
  knownFiles: string[];
  onSelect: (path: string) => void;
}) {
  const cached = guideCache.get(branch);
  const [steps, setSteps] = useState<GuideStep[] | null>(cached?.steps ?? null);
  const [done, setDone] = useState<Set<number>>(cached?.done ?? new Set());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(true);

  const generate = async () => {
    setBusy(true);
    setError(null);
    try {
      const prompt = await invoke<string>("render_review_guide_prompt", { branch });
      const result = await askMainAgent({
        branch,
        prompt,
        model: GUIDE_MODEL,
        effort: GUIDE_EFFORT,
      });
      if (!result?.ok || !result.text) {
        setError("The agent's turn failed — try again.");
        return;
      }
      const parsed = parseReviewGuide(result.text, knownFiles);
      if (!parsed) {
        setError("Could not parse a roadmap out of the reply — try regenerating.");
        return;
      }
      const fresh = new Set<number>();
      setSteps(parsed);
      setDone(fresh);
      setOpen(true);
      guideCache.set(branch, { steps: parsed, done: fresh });
    } finally {
      setBusy(false);
    }
  };

  const toggleDone = (index: number) => {
    setDone((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      const entry = guideCache.get(branch);
      if (entry) guideCache.set(branch, { ...entry, done: next });
      return next;
    });
  };

  return (
    <div className="review-guide">
      <div className="review-guide-header">
        <button
          className="small ghost review-guide-toggle"
          onClick={() => setOpen((o) => !o)}
          title="A step-by-step reading order for this diff, generated by the main agent"
        >
          <Icon name={open ? "chevron-down" : "chevron-right"} size={12} /> Review guide
          {steps && ` · ${done.size}/${steps.length}`}
        </button>
        <button
          className="small ghost"
          disabled={busy}
          onClick={() => void generate()}
          title="Ask the main agent to lay out the review order (core logic first, boilerplate last)"
        >
          {busy ? <Icon name="spinner" spin size={12} /> : <Icon name="bot" size={12} />}
          {steps ? "" : " Guide me"}
        </button>
      </div>

      {error && (
        <p className="hint warn" onClick={() => setError(null)} title="Click to dismiss">
          {error}
        </p>
      )}
      {busy && !steps && <p className="review-guide-empty">Reading the diff…</p>}

      {open && steps && (
        <ol className="review-guide-steps">
          {steps.map((step, i) => (
            <li key={i} className={`review-guide-step ${done.has(i) ? "done" : ""}`}>
              <div className="review-guide-step-head">
                <input
                  type="checkbox"
                  checked={done.has(i)}
                  onChange={() => toggleDone(i)}
                  title="Mark this step reviewed"
                />
                <button
                  className="review-guide-step-title"
                  onClick={() => onSelect(step.files[0])}
                  title={step.why || step.title}
                >
                  {step.title}
                </button>
                <span className={`review-guide-cat ${step.category}`}>
                  {CATEGORY_LABELS[step.category]}
                </span>
              </div>
              {step.why && <p className="review-guide-why">{step.why}</p>}
              <div className="review-guide-files">
                {step.files.map((f) => (
                  <button
                    key={f}
                    className="review-guide-file"
                    onClick={() => onSelect(f)}
                    title={f}
                  >
                    {f.split("/").pop()}
                  </button>
                ))}
              </div>
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}
